#! /bin/sh

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding 30
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config normal_border_color "#001A00"
bspc config focused_border_color "#00FF00"
bspc config presel_border_color "#FF8888"

maindesks="home emacs"
browdesks="www sms"
playdesks="com play"
extrdesks="pro1 pro2"

bspc monitor eDP1 -d $maindesks $browdesks $playdesks
bspc monitor DP1 -d $extrdesks

bspc rule -a Subl3 desktop=^2 follow=off
bspc rule -a Firefox desktop=^3 follow=off
bspc rule -a Telegram desktop=^4 follow=off
bspc rule -a Skype desktop=^5 follow=off
bspc rule -a Steam desktop=^6 follow=off

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    export PATH="$HOME/bin:$PATH"
fi

~/bin/panel &
~/.fehbg &
#sudo xboxdrv --detach-kernel-driver --mimic-xpad &
